import './global.css';
import {Box, CssBaseline, ThemeProvider} from "@mui/material";
import {theme} from "@/customTheme";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider theme={theme}>
          <CssBaseline/>
            <Box
                sx={{
                    fontFamily: 'DM Serif Display',
                }}
            >
                {children}
            </Box>
      </ThemeProvider>
      </body>
    </html>
  );
}

//'Serif Display', sans-serif
